- name: Container is running
  docker:
    image: progrium/consul
    name: consul
    hostname: "{{ ansible_hostname }}"
    ports:
      - 8500:8500
    command: -advertise {{ facter_ipaddress_eth1 }} {{ consul_extra }}
