- name: Container is running
  docker:
    image: progrium/consul
    name: consul
    hostname: "{{ ansible_hostname }}"
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 53:53/udp
    command: -advertise {{ facter_ipaddress_eth1 }} {{ consul_extra }}
